language: rust
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cargo test
        - rm target/debug/deps/libderive_new-*.so
        - cargo test --manifest-path testcrate/Cargo.toml

script:
  - cargo test
