[package]
name = "derive-new"
version = "0.4.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]
description = "`#[derive(new)]` implements simple constructor functions for structs and enums."
license = "MIT"
repository = "https://github.com/nrc/derive-new"

[lib]
proc-macro = true

[dependencies]
quote = "0.3"

[dependencies.syn]
version = "0.11"
features = ["full"]
